### ISSUE TITLE
Error 500 on Commit

### ISSUE THREAD

**Issue by toschulz** [odoucet/pdns-gui#5]
$domain = DomainPeer::retrieveByPK($audit->getDomainId()); in /lib/MyTools.class.php does not appear to return a valid object.  As a result $domain->getName(); and $domain->getId() both throw a error 500.

I'm running Ubuntu 12.04 and powerdns 3.0

**Comment by odoucet** [comment]
I've added a sample check, so that an error is thrown instead of just a 500 error.
